// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSqO0wYMxapXdi8OchfBaTCZk06GZ0q4',
    appId: '1:691794038265:web:a947d5e2fc6e3f1ab60128',
    messagingSenderId: '691794038265',
    projectId: 'cpplab-v03',
    authDomain: 'cpplab-v03.firebaseapp.com',
    databaseURL: 'https://cpplab-v03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpplab-v03.appspot.com',
    measurementId: 'G-NPTF08QD4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1N6dkL1NKxAuyzKz1NGf8cDtar1NecA8',
    appId: '1:691794038265:android:870ddefd5f54ea99b60128',
    messagingSenderId: '691794038265',
    projectId: 'cpplab-v03',
    databaseURL: 'https://cpplab-v03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpplab-v03.appspot.com',
  );
}
